### ISSUE TITLE
RHEL 8 Checklist wont import

### ISSUE THREAD

**Issue by zirus001** [NUWCDIVNPT/stig-manager#1148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of STIG Manager?

- [ ] I am using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases).
- [ ] I am NOT using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases). I am aware that the first thing I will be asked to do is update the application so that I have the latest bugfixes.

### Where are you experiencing the issue?

- [X] API
- [ ] UI or other client
- [ ] Deployment
- [ ] Elsewhere

### Current Behavior

When trying to import the RHEL 8 Checklist into the STIG Benchmarks. I am getting the following error message. I tried the V1R11 and the V1R12 Checklist.

{"sourceStack":"","name":"SyntaxError","message":"Unexpected token '<', \"<html>\r\n<h\"... is not valid JSON","stack":"SyntaxError: Unexpected token '<', \"<html>\r\n<h\"... is not valid JSON","env":{"version":"1.3.10","apiBase":"api","welcome":{"image":"","title":"","message":"","link":""},"commit":{"branch":"main","sha":"21f51923e0","tag":"na","describe":"1.3.10"},"oauth":{"authority":"https://csp-south-sman.cssp.hpc.mil/auth/realms/stigman","clientId":"stig-manager","refreshToken":{"disabled":false},"extraScopes":"","scopePrefix":"","claims":{"scope":"scope","username":"preferred_username","servicename":"clientId","name":"name","privileges":"['realm_access']?.['roles']","email":"email"}}}}

### Expected Behavior

Was expected to import the checklist as I have before.

### Describe your Environment

```markdown
- Hosting: Hosting our own Deployment of STIGMan.
- Browser: Chrome
- OS: RHEL7
- Node: 
- npm:
```

**Comment by cd-rite** [comment]
Hi @zirus001 I cannot replicate your problem, it imports fine for me! You are referring to importing the DISA reference STIG (`U_RHEL_8_V1R12_STIG.zip` or `U_RHEL_8_STIG_V1R12_Manual-xccdf.xml`, or as a part of the compilation library) into the "STIG Benchmarks" section of the "Application Management" interface, right?

![image](https://github.com/NUWCDIVNPT/stig-manager/assets/61710958/089489c9-c5f8-4049-8281-30a25411eae3)

**Comment by zirus001** [comment]
That is correct. I tried the standalone package as well as the zip and xml file within the zip. I will dig more into the error in the morning. Maybe try a reboot and see if there might be something on the OS level that's causing the issue. Since it's all in containers I don't think it would be but just in case.

**Comment by cd-rite** [comment]
That's very strange! Maybe try re-downloading the STIGs? 
It's only the RHEL 8 STIGs?

**Comment by csmig** [comment]
I also am not reproducing this, either with the latest release (1.3.13) or the version @zirus001 is running (1.3.10).

Please try updating to the latest release. If the issue persists please provide the entire JSON dump of the error report from the client side, and any error records emitted from the API. Also, please report which container image and tag you are using (:alpine or :ironbank from Docker Hub, or the UBS or slim image from Iron Bank).
Thanks.

**Comment by zirus001** [comment]
Good copy. Last night I did try updating to the 1.13.13 and re-downloading the file from cyber.mil with the same results. I had copied/pasted the original error before upgrading the image.

I'll grab that info this morning after our morning call.

**Comment by csmig** [comment]
I was hoping you had not provided the entire error object from the client because the one you pasted is missing file/line numbers in the `stack` or `sourceStack` properties. So this unusual scenario is even more perplexing to me for that reason as well.

Thanks for any further info, especially the container you are using.

**Comment by csmig** [comment]
Are you deploying STIG Manager with a reverse proxy in the path? If so, I have an idea that maybe you would be willing to rule in/out?  If not, then stop reading now and thanks.

The error message you are getting is consistent with the client receiving a non-JSON response body to the POST request it sent to the API to import a STIG. And the non-JSON snippet that you reported (`\r\r<h`) look suspiciously like a the start of an HTML response body. The API itself will never emit HTML, but an upstream proxy (like nginx) will if it is rejecting the request for any reason. The most common reason we see upstream proxies rejecting a request is a limit on the maximum size of the request body.

So perhaps you could please verify if any of my hypothesis seems to match your scenario. Thanks.

**Comment by csmig** [comment]
I'll be working issue #912 (redesigning the STIG import interface) in the next month or so. I am referencing that issue so I will be reminded of this one. I think it required too much cognitive effort to decipher the error report in this scenario. Upstream proxies getting upset and returning an HTML response is not uncommon and STIG Manager should provide better error feedback.
