### ISSUE TITLE
Checklist import issue (VMware vSphere 6.7 PostgreSQL)

### ISSUE THREAD

**Issue by TheTroubleshooter** [NUWCDIVNPT/stig-manager#743]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of STIG Manager?

- [X] I am using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases).
- [ ] I am NOT using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases). I am aware that the first thing I will be asked to do is update the application so that I have the latest bugfixes.

### Where are you experiencing the issue?

- [X] API
- [ ] UI or other client
- [ ] Deployment
- [ ] Elsewhere

### Current Behavior

When importing VMware vSphere 6.7 PostgreSQL completed checklists STIG Manager will only import 3 of the 22 rules and findings even though the checklist is fully completed. If you ignore the issue and fill out the checklist manually the API will show incorrect percentages and numbers throughout the interfaces. I have verified the issue on two installations of STIG Manager, see attached photos.

### Expected Behavior

STIG Manager should import all of the rules present in the checklist

### Steps To Reproduce

Create and complete the VMware vSphere 6.7 PostgreSQL checklist in Stig Viewer and import into STIG Manager.

### Can you provide screenshots, logs, or other useful artifacts?

<img width="656" alt="VMware PostgreSQL 3" src="https://user-images.githubusercontent.com/68762193/186193485-9f60404b-5c07-4d7d-9464-1c7f0f485dd3.PNG">
<img width="464" alt="VMware PostgreSQL 2" src="https://user-images.githubusercontent.com/68762193/186193487-bd53ce2c-ca89-4a75-b597-dd8b45e5231d.PNG">
<img width="232" alt="VMware PostgreSQL 1" src="https://user-images.githubusercontent.com/68762193/186193488-aaec9e31-6c0f-444b-86c2-4d565194c7e8.PNG">

### Describe your Environment

```markdown
- Hosting:
- Browser:
- OS:
- Node:
- npm:
```

**Comment by cd-rite** [comment]
Closing this issue and assuming the work-around is sufficient. For STIGs with identical release information, users will have to choose which one they want to use in the system, or manually change their reference STIG to keep them separate.
