### ISSUE TITLE
Offer a Metrics Overview that can span multiple Collections. 

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stig-manager#848]
Provide a mechanism for Users to combine multiple Collections into one Overview panel display. The panel would show their overall combined high-level metrics,  with a navigable grid to the right with the contributing Collections.
Similar to current Metrics panel, but rather than the various Aggregations offered on right-hand side, the component Collections would be displayed. Clicking an icon (or double-clicking) on the component Collection would open the Metrics tab for that particular Collection.

```[tasklist]
### Tasks
- [ ] https://github.com/NUWCDIVNPT/stig-manager/issues/1177
- [ ] https://github.com/NUWCDIVNPT/stig-manager/issues/1178
- [ ] https://github.com/NUWCDIVNPT/stig-manager/issues/1179
```
